modLoader = "javafml" #mandatory
loaderVersion = "[43,)"
license = "MIT"
[[mods]] #mandatory
modId = "mechanicalsifting" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "MechanicalSifting" #mandatory
authors = "Bennyboy1695" #optional
description = '''
A sifting mod making use of creates "power" system
'''
[[dependencies.mechanicalsifting]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.mechanicalsifting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"
