modLoader = "javafml" #mandatory
loaderVersion = "[43,)"
license = "MIT"
[[mods]] #mandatory
modId = "mechanicalmachinery" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "MechanicalMachinery" #mandatory
authors = "Bennyboy1695" #optional
description = '''
A mod adding machines that makes use of creates 'power' system
'''
[[dependencies.mechanicalmachinery]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.mechanicalmachinery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"
